"""campaign_redesign_fields

Revision ID: 2be06766d687
Revises: ec2b9cc831b6
Create Date: 2026-04-17 17:00:31.942659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be06766d687'
down_revision: Union[str, Sequence[str], None] = 'ec2b9cc831b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_keywords', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mention_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('selected_presets', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sets_per_video', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_campaigns_preset_id_v2', 'presets', ['preset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaigns_preset_id_v2', type_='foreignkey')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('target_count')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('sets_per_video')
        batch_op.drop_column('selected_presets')
        batch_op.drop_column('mention_style')
        batch_op.drop_column('target_keywords')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
