"""brand_weekly_goal

Revision ID: 49778c080ca0
Revises: 560d749e482c
Create Date: 2026-04-16 16:04:47.335637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49778c080ca0'
down_revision: Union[str, Sequence[str], None] = '560d749e482c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_campaign_target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_campaign_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('auto_campaign_enabled')
        batch_op.drop_column('weekly_campaign_target')

    # ### end Alembic commands ###
