"""v2_multi_machine_tables

Revision ID: 560d749e482c
Revises: 7dfc3d2a87d0
Create Date: 2026-04-16 15:11:45.816525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560d749e482c'
down_revision: Union[str, Sequence[str], None] = '7dfc3d2a87d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.create_index('idx_presets_code', ['code'], unique=False)

    op.create_table('workers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ip_method', sa.String(), nullable=True),
    sa.Column('ip_config', sa.Text(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('os_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index('idx_workers_status', ['status'], unique=False)

    op.create_table('profile_locks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('adspower_profile_id', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_locks', schema=None) as batch_op:
        batch_op.create_index('idx_locks_account', ['account_id'], unique=False)
        batch_op.create_index('idx_locks_active', ['released_at'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('campaign_step_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['campaign_step_id'], ['campaign_steps.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_priority_status', ['priority', 'status'], unique=False)
        batch_op.create_index('idx_tasks_scheduled', ['scheduled_at'], unique=False)
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_tasks_worker', ['worker_id'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_comment_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_like_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weekly_comment_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weekly_like_limit', sa.Integer(), nullable=True))

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comment_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('preset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_campaigns_preset_id', 'presets', ['preset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaigns_preset_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('preset_id')
        batch_op.drop_column('comment_mode')
        batch_op.drop_column('campaign_type')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('weekly_like_limit')
        batch_op.drop_column('weekly_comment_limit')
        batch_op.drop_column('daily_like_limit')
        batch_op.drop_column('daily_comment_limit')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_worker')
        batch_op.drop_index('idx_tasks_status')
        batch_op.drop_index('idx_tasks_scheduled')
        batch_op.drop_index('idx_tasks_priority_status')

    op.drop_table('tasks')
    with op.batch_alter_table('profile_locks', schema=None) as batch_op:
        batch_op.drop_index('idx_locks_active')
        batch_op.drop_index('idx_locks_account')

    op.drop_table('profile_locks')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index('idx_workers_status')

    op.drop_table('workers')
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_index('idx_presets_code')

    op.drop_table('presets')
    # ### end Alembic commands ###
