"""campaign_video_id_nullable

Revision ID: 5ae7d3c20819
Revises: 2be06766d687
Create Date: 2026-04-17 19:22:56.561647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae7d3c20819'
down_revision: Union[str, Sequence[str], None] = '2be06766d687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
