"""add comment_snapshots table for ranking analytics

Revision ID: 6e20c5219262
Revises: d2f6a8b3c437
Create Date: 2026-04-26 21:18:53.633336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e20c5219262'
down_revision: Union[str, Sequence[str], None] = 'd2f6a8b3c437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('youtube_comment_id', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rank_scope', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('visible_to_third_party', sa.Boolean(), nullable=True),
    sa.Column('is_held', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('captured_by_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['captured_by_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snap_account', ['account_id', 'captured_at'], unique=False)
        batch_op.create_index('idx_snap_video_time', ['video_id', 'captured_at'], unique=False)
        batch_op.create_index('idx_snap_yt_id', ['youtube_comment_id', 'captured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_snap_yt_id')
        batch_op.drop_index('idx_snap_video_time')
        batch_op.drop_index('idx_snap_account')

    op.drop_table('comment_snapshots')
    # ### end Alembic commands ###
