"""add recovery_emails table

Revision ID: 7da2a699d459
Revises: 56b9dedf1f5b
Create Date: 2026-04-14 13:31:02.193067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da2a699d459'
down_revision: Union[str, Sequence[str], None] = '56b9dedf1f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('imap_host', sa.String(), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('used_by_account_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['used_by_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('recovery_emails', schema=None) as batch_op:
        batch_op.create_index('idx_recovery_available', ['disabled', 'used_by_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_emails', schema=None) as batch_op:
        batch_op.drop_index('idx_recovery_available')

    op.drop_table('recovery_emails')
    # ### end Alembic commands ###
