"""add persona_slots table

Revision ID: 7dfc3d2a87d0
Revises: 7da2a699d459
Create Date: 2026-04-15 17:30:53.501308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfc3d2a87d0'
down_revision: Union[str, Sequence[str], None] = '7da2a699d459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('occupation', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('device_hint', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('assigned_account_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persona_slots', schema=None) as batch_op:
        batch_op.create_index('idx_slot_demo', ['age', 'gender', 'occupation'], unique=False)
        batch_op.create_index('idx_slot_used', ['used'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona_slots', schema=None) as batch_op:
        batch_op.drop_index('idx_slot_used')
        batch_op.drop_index('idx_slot_demo')

    op.drop_table('persona_slots')
    # ### end Alembic commands ###
