"""brand_promo_keywords_selected_presets

Revision ID: ec2b9cc831b6
Revises: 200fbaac2ba0
Create Date: 2026-04-17 13:57:26.333807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2b9cc831b6'
down_revision: Union[str, Sequence[str], None] = '200fbaac2ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_keywords', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('selected_presets', sa.Text(), nullable=True))

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_campaigns_preset_id', 'presets', ['preset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaigns_preset_id', type_='foreignkey')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('selected_presets')
        batch_op.drop_column('promo_keywords')

    # ### end Alembic commands ###
