/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWorkersIndexRouteImport } from './routes/_authenticated/workers/index'
import { Route as AuthenticatedVideosIndexRouteImport } from './routes/_authenticated/videos/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedTargetsIndexRouteImport } from './routes/_authenticated/targets/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns/index'
import { Route as AuthenticatedBrandsIndexRouteImport } from './routes/_authenticated/brands/index'
import { Route as AuthenticatedAvatarsIndexRouteImport } from './routes/_authenticated/avatars/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'
import { Route as AuthenticatedWorkersIpMonitorRouteImport } from './routes/_authenticated/workers/ip-monitor'
import { Route as AuthenticatedWorkersErrorsRouteImport } from './routes/_authenticated/workers/errors'
import { Route as AuthenticatedVideosVideoIdRouteImport } from './routes/_authenticated/videos/$videoId'
import { Route as AuthenticatedSettingsPresetsRouteImport } from './routes/_authenticated/settings/presets'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsBehaviorRouteImport } from './routes/_authenticated/settings/behavior'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedProductsBrandIdIndexRouteImport } from './routes/_authenticated/products/$brandId/index'
import { Route as AuthenticatedProductsBrandIdNichesNicheIdRouteRouteImport } from './routes/_authenticated/products/$brandId/niches/$nicheId/route'
import { Route as AuthenticatedProductsBrandIdNichesNicheIdIndexRouteImport } from './routes/_authenticated/products/$brandId/niches/$nicheId/index'
import { Route as AuthenticatedProductsBrandIdNichesNicheIdMessagingRouteImport } from './routes/_authenticated/products/$brandId/niches/$nicheId/messaging'
import { Route as AuthenticatedProductsBrandIdNichesNicheIdCollectionRouteImport } from './routes/_authenticated/products/$brandId/niches/$nicheId/collection'
import { Route as AuthenticatedProductsBrandIdNichesNicheIdCampaignsRouteImport } from './routes/_authenticated/products/$brandId/niches/$nicheId/campaigns'
import { Route as AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRouteImport } from './routes/_authenticated/products/$brandId/niches/$nicheId/analytics'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersIndexRoute =
  AuthenticatedWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideosIndexRoute =
  AuthenticatedVideosIndexRouteImport.update({
    id: '/videos/',
    path: '/videos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTargetsIndexRoute =
  AuthenticatedTargetsIndexRouteImport.update({
    id: '/targets/',
    path: '/targets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsIndexRoute =
  AuthenticatedBrandsIndexRouteImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvatarsIndexRoute =
  AuthenticatedAvatarsIndexRouteImport.update({
    id: '/avatars/',
    path: '/avatars/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersIpMonitorRoute =
  AuthenticatedWorkersIpMonitorRouteImport.update({
    id: '/workers/ip-monitor',
    path: '/workers/ip-monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersErrorsRoute =
  AuthenticatedWorkersErrorsRouteImport.update({
    id: '/workers/errors',
    path: '/workers/errors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideosVideoIdRoute =
  AuthenticatedVideosVideoIdRouteImport.update({
    id: '/videos/$videoId',
    path: '/videos/$videoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPresetsRoute =
  AuthenticatedSettingsPresetsRouteImport.update({
    id: '/presets',
    path: '/presets',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBehaviorRoute =
  AuthenticatedSettingsBehaviorRouteImport.update({
    id: '/behavior',
    path: '/behavior',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsBrandIdIndexRoute =
  AuthenticatedProductsBrandIdIndexRouteImport.update({
    id: '/products/$brandId/',
    path: '/products/$brandId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsBrandIdNichesNicheIdRouteRoute =
  AuthenticatedProductsBrandIdNichesNicheIdRouteRouteImport.update({
    id: '/products/$brandId/niches/$nicheId',
    path: '/products/$brandId/niches/$nicheId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsBrandIdNichesNicheIdIndexRoute =
  AuthenticatedProductsBrandIdNichesNicheIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsBrandIdNichesNicheIdRouteRoute,
  } as any)
const AuthenticatedProductsBrandIdNichesNicheIdMessagingRoute =
  AuthenticatedProductsBrandIdNichesNicheIdMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => AuthenticatedProductsBrandIdNichesNicheIdRouteRoute,
  } as any)
const AuthenticatedProductsBrandIdNichesNicheIdCollectionRoute =
  AuthenticatedProductsBrandIdNichesNicheIdCollectionRouteImport.update({
    id: '/collection',
    path: '/collection',
    getParentRoute: () => AuthenticatedProductsBrandIdNichesNicheIdRouteRoute,
  } as any)
const AuthenticatedProductsBrandIdNichesNicheIdCampaignsRoute =
  AuthenticatedProductsBrandIdNichesNicheIdCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedProductsBrandIdNichesNicheIdRouteRoute,
  } as any)
const AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRoute =
  AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedProductsBrandIdNichesNicheIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/behavior': typeof AuthenticatedSettingsBehaviorRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/presets': typeof AuthenticatedSettingsPresetsRoute
  '/videos/$videoId': typeof AuthenticatedVideosVideoIdRoute
  '/workers/errors': typeof AuthenticatedWorkersErrorsRoute
  '/workers/ip-monitor': typeof AuthenticatedWorkersIpMonitorRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/avatars/': typeof AuthenticatedAvatarsIndexRoute
  '/brands/': typeof AuthenticatedBrandsIndexRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/targets/': typeof AuthenticatedTargetsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/videos/': typeof AuthenticatedVideosIndexRoute
  '/workers/': typeof AuthenticatedWorkersIndexRoute
  '/products/$brandId/': typeof AuthenticatedProductsBrandIdIndexRoute
  '/products/$brandId/niches/$nicheId': typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRouteWithChildren
  '/products/$brandId/niches/$nicheId/analytics': typeof AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRoute
  '/products/$brandId/niches/$nicheId/campaigns': typeof AuthenticatedProductsBrandIdNichesNicheIdCampaignsRoute
  '/products/$brandId/niches/$nicheId/collection': typeof AuthenticatedProductsBrandIdNichesNicheIdCollectionRoute
  '/products/$brandId/niches/$nicheId/messaging': typeof AuthenticatedProductsBrandIdNichesNicheIdMessagingRoute
  '/products/$brandId/niches/$nicheId/': typeof AuthenticatedProductsBrandIdNichesNicheIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/behavior': typeof AuthenticatedSettingsBehaviorRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/presets': typeof AuthenticatedSettingsPresetsRoute
  '/videos/$videoId': typeof AuthenticatedVideosVideoIdRoute
  '/workers/errors': typeof AuthenticatedWorkersErrorsRoute
  '/workers/ip-monitor': typeof AuthenticatedWorkersIpMonitorRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/avatars': typeof AuthenticatedAvatarsIndexRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/targets': typeof AuthenticatedTargetsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/videos': typeof AuthenticatedVideosIndexRoute
  '/workers': typeof AuthenticatedWorkersIndexRoute
  '/products/$brandId': typeof AuthenticatedProductsBrandIdIndexRoute
  '/products/$brandId/niches/$nicheId/analytics': typeof AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRoute
  '/products/$brandId/niches/$nicheId/campaigns': typeof AuthenticatedProductsBrandIdNichesNicheIdCampaignsRoute
  '/products/$brandId/niches/$nicheId/collection': typeof AuthenticatedProductsBrandIdNichesNicheIdCollectionRoute
  '/products/$brandId/niches/$nicheId/messaging': typeof AuthenticatedProductsBrandIdNichesNicheIdMessagingRoute
  '/products/$brandId/niches/$nicheId': typeof AuthenticatedProductsBrandIdNichesNicheIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/behavior': typeof AuthenticatedSettingsBehaviorRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/presets': typeof AuthenticatedSettingsPresetsRoute
  '/_authenticated/videos/$videoId': typeof AuthenticatedVideosVideoIdRoute
  '/_authenticated/workers/errors': typeof AuthenticatedWorkersErrorsRoute
  '/_authenticated/workers/ip-monitor': typeof AuthenticatedWorkersIpMonitorRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/avatars/': typeof AuthenticatedAvatarsIndexRoute
  '/_authenticated/brands/': typeof AuthenticatedBrandsIndexRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/targets/': typeof AuthenticatedTargetsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/videos/': typeof AuthenticatedVideosIndexRoute
  '/_authenticated/workers/': typeof AuthenticatedWorkersIndexRoute
  '/_authenticated/products/$brandId/': typeof AuthenticatedProductsBrandIdIndexRoute
  '/_authenticated/products/$brandId/niches/$nicheId': typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRouteWithChildren
  '/_authenticated/products/$brandId/niches/$nicheId/analytics': typeof AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRoute
  '/_authenticated/products/$brandId/niches/$nicheId/campaigns': typeof AuthenticatedProductsBrandIdNichesNicheIdCampaignsRoute
  '/_authenticated/products/$brandId/niches/$nicheId/collection': typeof AuthenticatedProductsBrandIdNichesNicheIdCollectionRoute
  '/_authenticated/products/$brandId/niches/$nicheId/messaging': typeof AuthenticatedProductsBrandIdNichesNicheIdMessagingRoute
  '/_authenticated/products/$brandId/niches/$nicheId/': typeof AuthenticatedProductsBrandIdNichesNicheIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/behavior'
    | '/settings/display'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/presets'
    | '/videos/$videoId'
    | '/workers/errors'
    | '/workers/ip-monitor'
    | '/accounts/'
    | '/analytics/'
    | '/audit/'
    | '/avatars/'
    | '/brands/'
    | '/campaigns/'
    | '/onboarding/'
    | '/products/'
    | '/settings/'
    | '/targets/'
    | '/tasks/'
    | '/videos/'
    | '/workers/'
    | '/products/$brandId/'
    | '/products/$brandId/niches/$nicheId'
    | '/products/$brandId/niches/$nicheId/analytics'
    | '/products/$brandId/niches/$nicheId/campaigns'
    | '/products/$brandId/niches/$nicheId/collection'
    | '/products/$brandId/niches/$nicheId/messaging'
    | '/products/$brandId/niches/$nicheId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/behavior'
    | '/settings/display'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/presets'
    | '/videos/$videoId'
    | '/workers/errors'
    | '/workers/ip-monitor'
    | '/accounts'
    | '/analytics'
    | '/audit'
    | '/avatars'
    | '/brands'
    | '/campaigns'
    | '/onboarding'
    | '/products'
    | '/settings'
    | '/targets'
    | '/tasks'
    | '/videos'
    | '/workers'
    | '/products/$brandId'
    | '/products/$brandId/niches/$nicheId/analytics'
    | '/products/$brandId/niches/$nicheId/campaigns'
    | '/products/$brandId/niches/$nicheId/collection'
    | '/products/$brandId/niches/$nicheId/messaging'
    | '/products/$brandId/niches/$nicheId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/login'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/behavior'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/presets'
    | '/_authenticated/videos/$videoId'
    | '/_authenticated/workers/errors'
    | '/_authenticated/workers/ip-monitor'
    | '/_authenticated/accounts/'
    | '/_authenticated/analytics/'
    | '/_authenticated/audit/'
    | '/_authenticated/avatars/'
    | '/_authenticated/brands/'
    | '/_authenticated/campaigns/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/products/'
    | '/_authenticated/settings/'
    | '/_authenticated/targets/'
    | '/_authenticated/tasks/'
    | '/_authenticated/videos/'
    | '/_authenticated/workers/'
    | '/_authenticated/products/$brandId/'
    | '/_authenticated/products/$brandId/niches/$nicheId'
    | '/_authenticated/products/$brandId/niches/$nicheId/analytics'
    | '/_authenticated/products/$brandId/niches/$nicheId/campaigns'
    | '/_authenticated/products/$brandId/niches/$nicheId/collection'
    | '/_authenticated/products/$brandId/niches/$nicheId/messaging'
    | '/_authenticated/products/$brandId/niches/$nicheId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/': {
      id: '/_authenticated/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AuthenticatedWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos/': {
      id: '/_authenticated/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof AuthenticatedVideosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/targets/': {
      id: '/_authenticated/targets/'
      path: '/targets'
      fullPath: '/targets/'
      preLoaderRoute: typeof AuthenticatedTargetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/': {
      id: '/_authenticated/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AuthenticatedBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avatars/': {
      id: '/_authenticated/avatars/'
      path: '/avatars'
      fullPath: '/avatars/'
      preLoaderRoute: typeof AuthenticatedAvatarsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/ip-monitor': {
      id: '/_authenticated/workers/ip-monitor'
      path: '/workers/ip-monitor'
      fullPath: '/workers/ip-monitor'
      preLoaderRoute: typeof AuthenticatedWorkersIpMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/errors': {
      id: '/_authenticated/workers/errors'
      path: '/workers/errors'
      fullPath: '/workers/errors'
      preLoaderRoute: typeof AuthenticatedWorkersErrorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos/$videoId': {
      id: '/_authenticated/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof AuthenticatedVideosVideoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/presets': {
      id: '/_authenticated/settings/presets'
      path: '/presets'
      fullPath: '/settings/presets'
      preLoaderRoute: typeof AuthenticatedSettingsPresetsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/behavior': {
      id: '/_authenticated/settings/behavior'
      path: '/behavior'
      fullPath: '/settings/behavior'
      preLoaderRoute: typeof AuthenticatedSettingsBehaviorRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$brandId/': {
      id: '/_authenticated/products/$brandId/'
      path: '/products/$brandId'
      fullPath: '/products/$brandId/'
      preLoaderRoute: typeof AuthenticatedProductsBrandIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$brandId/niches/$nicheId': {
      id: '/_authenticated/products/$brandId/niches/$nicheId'
      path: '/products/$brandId/niches/$nicheId'
      fullPath: '/products/$brandId/niches/$nicheId'
      preLoaderRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$brandId/niches/$nicheId/': {
      id: '/_authenticated/products/$brandId/niches/$nicheId/'
      path: '/'
      fullPath: '/products/$brandId/niches/$nicheId/'
      preLoaderRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdIndexRouteImport
      parentRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRoute
    }
    '/_authenticated/products/$brandId/niches/$nicheId/messaging': {
      id: '/_authenticated/products/$brandId/niches/$nicheId/messaging'
      path: '/messaging'
      fullPath: '/products/$brandId/niches/$nicheId/messaging'
      preLoaderRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdMessagingRouteImport
      parentRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRoute
    }
    '/_authenticated/products/$brandId/niches/$nicheId/collection': {
      id: '/_authenticated/products/$brandId/niches/$nicheId/collection'
      path: '/collection'
      fullPath: '/products/$brandId/niches/$nicheId/collection'
      preLoaderRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdCollectionRouteImport
      parentRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRoute
    }
    '/_authenticated/products/$brandId/niches/$nicheId/campaigns': {
      id: '/_authenticated/products/$brandId/niches/$nicheId/campaigns'
      path: '/campaigns'
      fullPath: '/products/$brandId/niches/$nicheId/campaigns'
      preLoaderRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdCampaignsRouteImport
      parentRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRoute
    }
    '/_authenticated/products/$brandId/niches/$nicheId/analytics': {
      id: '/_authenticated/products/$brandId/niches/$nicheId/analytics'
      path: '/analytics'
      fullPath: '/products/$brandId/niches/$nicheId/analytics'
      preLoaderRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsBehaviorRoute: typeof AuthenticatedSettingsBehaviorRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPresetsRoute: typeof AuthenticatedSettingsPresetsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsBehaviorRoute: AuthenticatedSettingsBehaviorRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPresetsRoute: AuthenticatedSettingsPresetsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedProductsBrandIdNichesNicheIdRouteRouteChildren {
  AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRoute
  AuthenticatedProductsBrandIdNichesNicheIdCampaignsRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdCampaignsRoute
  AuthenticatedProductsBrandIdNichesNicheIdCollectionRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdCollectionRoute
  AuthenticatedProductsBrandIdNichesNicheIdMessagingRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdMessagingRoute
  AuthenticatedProductsBrandIdNichesNicheIdIndexRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdIndexRoute
}

const AuthenticatedProductsBrandIdNichesNicheIdRouteRouteChildren: AuthenticatedProductsBrandIdNichesNicheIdRouteRouteChildren =
  {
    AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRoute:
      AuthenticatedProductsBrandIdNichesNicheIdAnalyticsRoute,
    AuthenticatedProductsBrandIdNichesNicheIdCampaignsRoute:
      AuthenticatedProductsBrandIdNichesNicheIdCampaignsRoute,
    AuthenticatedProductsBrandIdNichesNicheIdCollectionRoute:
      AuthenticatedProductsBrandIdNichesNicheIdCollectionRoute,
    AuthenticatedProductsBrandIdNichesNicheIdMessagingRoute:
      AuthenticatedProductsBrandIdNichesNicheIdMessagingRoute,
    AuthenticatedProductsBrandIdNichesNicheIdIndexRoute:
      AuthenticatedProductsBrandIdNichesNicheIdIndexRoute,
  }

const AuthenticatedProductsBrandIdNichesNicheIdRouteRouteWithChildren =
  AuthenticatedProductsBrandIdNichesNicheIdRouteRoute._addFileChildren(
    AuthenticatedProductsBrandIdNichesNicheIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedVideosVideoIdRoute: typeof AuthenticatedVideosVideoIdRoute
  AuthenticatedWorkersErrorsRoute: typeof AuthenticatedWorkersErrorsRoute
  AuthenticatedWorkersIpMonitorRoute: typeof AuthenticatedWorkersIpMonitorRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedAvatarsIndexRoute: typeof AuthenticatedAvatarsIndexRoute
  AuthenticatedBrandsIndexRoute: typeof AuthenticatedBrandsIndexRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedTargetsIndexRoute: typeof AuthenticatedTargetsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedVideosIndexRoute: typeof AuthenticatedVideosIndexRoute
  AuthenticatedWorkersIndexRoute: typeof AuthenticatedWorkersIndexRoute
  AuthenticatedProductsBrandIdIndexRoute: typeof AuthenticatedProductsBrandIdIndexRoute
  AuthenticatedProductsBrandIdNichesNicheIdRouteRoute: typeof AuthenticatedProductsBrandIdNichesNicheIdRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedVideosVideoIdRoute: AuthenticatedVideosVideoIdRoute,
  AuthenticatedWorkersErrorsRoute: AuthenticatedWorkersErrorsRoute,
  AuthenticatedWorkersIpMonitorRoute: AuthenticatedWorkersIpMonitorRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedAvatarsIndexRoute: AuthenticatedAvatarsIndexRoute,
  AuthenticatedBrandsIndexRoute: AuthenticatedBrandsIndexRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedTargetsIndexRoute: AuthenticatedTargetsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedVideosIndexRoute: AuthenticatedVideosIndexRoute,
  AuthenticatedWorkersIndexRoute: AuthenticatedWorkersIndexRoute,
  AuthenticatedProductsBrandIdIndexRoute:
    AuthenticatedProductsBrandIdIndexRoute,
  AuthenticatedProductsBrandIdNichesNicheIdRouteRoute:
    AuthenticatedProductsBrandIdNichesNicheIdRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
